### ISSUE TITLE
SBU text file

### ISSUE THREAD

**Issue by maja601** [stevewongv/DSC-PyTorch#1]
Hi,

could you please specify what exactly **SBU.txt** contains or where you got it from?
Is it possible to run the Code with the regular SBU dataset?

Thank you in advance!

**Comment by stevewongv** [comment]
It can be generated by writing a simple script. The format is Image path + ‘ ‘ + mask path\n.

**Comment by maja601** [comment]
Ah, I see. Thank you, I found the line.
What are the advantages over loading the images directly?
Is it faster than `next(os.walk(image_dir))`?

**Comment by stevewongv** [comment]
> Ah, I see. Thank you, I found the line.
> What are the advantages over loading the images directly?
> Is it faster than `next(os.walk(image_dir))`?

Just personal choice.
