### ISSUE TITLE
程序运行问题

### ISSUE THREAD

**Issue by wangyuxuan-123** [stevewongv/DSC-PyTorch#10]
运行测试和训练需要在SBU.txt中进行地址读取，在数据集中没有相关文件，请问该文件的内容和格式是什么？

**Comment by stevewongv** [comment]
https://github.com/stevewongv/DSC-PyTorch/blob/0ebde182bf9ee78adf403fbd52167afa6618a97c/dataset.py#L65-L67

**Comment by JustinhoCHN** [comment]
@wangyuxuan-123 请问预训练权重您可以用网盘再分享下吗？作者的这个权重的链接已经失效下不了了，谢谢。
