### ISSUE TITLE
评测结果计算问题

### ISSUE THREAD

**Issue by Nora919530829** [stevewongv/DSC-PyTorch#12]
非常感谢分享，想请教一下你的BER和Accuracy的评测指标代码是怎么计算的？我按照论文写的，用你提供的预训练模型得到的acc只有0,95，而BER只有9.1，无法达到你给出的结果。想请教一下。谢谢啦！

**Comment by JustinhoCHN** [comment]
@Nora919530829 请问预训练权重您可以用网盘再分享下吗？作者的这个权重的链接已经失效下不了了，谢谢。
