### ISSUE TITLE
pretrained model的谷歌网盘链接失效了，麻烦重发一下？

### ISSUE THREAD

**Issue by JustinhoCHN** [stevewongv/DSC-PyTorch#13]
https://drive.google.com/file/d/17VfUOu5xwHHc3M05N0oCjF2FGGirw7gt/view?usp=sharing
这个链接已经找不到了。

**Comment by JustinhoCHN** [comment]
自己是用SBU数据重新训练后解决，4卡2080ti一小时不到就训练完了。

**Comment by LeDinhManh-tech** [comment]
Can you share the weight file with me? Please

**Comment by stevewongv** [comment]
Update weight.

**Comment by 1022WANG** [comment]
> 自己是用SBU数据重新训练后解决，4卡2080ti一小时不到就训练完了。

你好，请问一下这篇文章你成功复现了嘛！想要请教一些问题不知道是否方便呢？
