### ISSUE TITLE
Upload evaluation code

### ISSUE THREAD

**Issue by Roujack** [stevewongv/DSC-PyTorch#3]
Hi， can you upload the evaluation code about BER for shadow detection and RMSE for shadow removal?

**Comment by stevewongv** [comment]
> Hi， can you upload the evaluation code about BER for shadow detection and RMSE for shadow removal?

You can find them in GitHub. Or just google it.

**Comment by Roujack** [comment]
yeah, I've tried, but nothing found. St-GAN, maskShadowGAN, and other repository didn't provide the evaluation code, which puzzles me. I write my own evaluation code(when calculate the RMSE, I treat each pixel with 3 channel as a data point), but the result is far from the value reported in the paper.
