### ISSUE TITLE
阴影检测测试结果问题

### ISSUE THREAD

**Issue by Alice-ren** [stevewongv/DSC-PyTorch#4]
非常感谢你的分享，我在执行python main.py -a test 通过预训练模型的得到的结果有点奇怪，图中标记的阴影位置都在右上角，不知道问题在哪里

**Comment by stevewongv** [comment]
可以给个图看一下吗？

**Comment by Alice-ren** [comment]
我把结果放在这个仓库里了，SBU-Test是测试的原图和mask，results里面是有问题的结果图像[https://github.com/Alice-ren/shadow_detection_results](url)

**Comment by JustinhoCHN** [comment]
@Alice-ren 请问预训练权重您可以用网盘再分享下吗？作者的这个权重的链接已经失效下不了了，谢谢。

**Comment by GuLicheng** [comment]
> 非常感谢你的分享，我在执行python main.py -a test 通过预训练模型的得到的结果有点奇怪，图中标记的阴影位置都在右上角，不知道问题在哪里

您好，请问您有UCF数据集吗？我在网上搜寻了很久但是没有找到这个数据集，如果有的话可以分享我一个能下载数据集的链接吗？非常感谢。

**Comment by DuoAp** [comment]
最后解决了吗？ 我也遇到这个问题了， 用的是预训练的模型，用main.py 测试的
