### ISSUE TITLE
result图片问题

### ISSUE THREAD

**Issue by yunww12** [stevewongv/DSC-PyTorch#6]
你好，请问最后的result图片需要用CRF处理吗

**Comment by stevewongv** [comment]
https://github.com/stevewongv/DSC-PyTorch/blob/0ebde182bf9ee78adf403fbd52167afa6618a97c/main.py#L286

**Comment by yunww12** [comment]
![1](https://user-images.githubusercontent.com/56508821/77845689-68eb7e00-71e3-11ea-8d0f-8d0cc3c8e6e4.jpg)
![1](https://user-images.githubusercontent.com/56508821/77845702-7b65b780-71e3-11ea-9da5-3b6e781b3c9d.png)
这是原图和结果图，需要对结果图进行阈值化得到最后的Mask吗

**Comment by stevewongv** [comment]
等下周我有空跑一下，谢谢提供问题

**Comment by yunww12** [comment]
谢谢你抽空回复，我补充一下一些细节：我下载了Google drive中的模型，在进行测试时得到了以上的结果。

**Comment by yunww12** [comment]
你好，这个问题解决了，是我的参数输入不对，谢谢你的帮助！

**Comment by JustinhoCHN** [comment]
@Dovakejin  请问预训练权重您可以用网盘再分享下吗？作者的这个权重的链接已经失效下不了了，谢谢。
