### ISSUE TITLE
网络训练不收敛

### ISSUE THREAD

**Issue by HusterRC** [stevewongv/DSC-PyTorch#8]
网络训练SBU数据集无法收敛

**Comment by stevewongv** [comment]
Pytorch版本是多少

**Comment by HusterRC** [comment]
@stevewongv pytorch版本1.2。仔细看了一下代码，发现loss与论文作者不一样，其他的没啥比较大的改变

**Comment by HusterRC** [comment]
@stevewongv  layer4_context = torch.cat((layer4_conv2, layer4_dsc), 1)，这里contact feature map作用大吗？

**Comment by stevewongv** [comment]
> @stevewongv pytorch版本1.2。仔细看了一下代码，发现loss与论文作者不一样，其他的没啥比较大的改变

readme提到了 要用0.4.1

**Comment by HusterRC** [comment]
@stevewongv 恩啊，版本差异也不可能这么大吧！

**Comment by HusterRC** [comment]
> > @stevewongv pytorch版本1.2。仔细看了一下代码，发现loss与论文作者不一样，其他的没啥比较大的改变
> 
> readme提到了 要用0.4.1

版本训练差异不可能这么大吧

**Comment by stevewongv** [comment]
> > > @stevewongv pytorch版本1.2。仔细看了一下代码，发现loss与论文作者不一样，其他的没啥比较大的改变
> > 
> > readme提到了 要用0.4.1
> 
> 版本训练差异不可能这么大吧

里面提及了1.x版本训练有问题。这是我的试验结果，你自己可以尝试。
